name: CI & CD

on:
  push:
    branches: [ "main" ]

env:
  COMPOSE_FILE: docker-compose.prod.yml

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run API tests
        run: |
          docker compose -f docker-compose.yml run --rm tailor_api mix test

      - name: Run Front-end tests
        run: |
          docker compose -f docker-compose.yml run --rm tailor-frontend npm test -- --ci --passWithNoTests

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: prod

    steps:
      - name: Checkout repository (for rsync)
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e
            cd ~/tailor
            git pull origin main
            docker compose -f ${{ env.COMPOSE_FILE }} up -d --build
            docker system prune -af --volumes --filter "until=24h" 